services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/opt/app
    links:
      - postgres
    networks:
      - default

  nginx:
    image: nginx:1.26.0-alpine3.19
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
    volumes:
      - ./docker/nginx/config:/etc/nginx:ro
      - ./src/public:/opt/app/public
    links:
      - php
    networks:
      - default

  postgres:
    image: postgres:16.3
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres-volume:
